__author__ = 'steveniemitz'
from thrift.transport import TTransport

from src.dispatch import MuxMessageDispatcher
from src.scales import Scales
from src.thealthysocket import THealthySocket


_MUXERS = {}
class MuxDispatcherProvider(object):
  @staticmethod
  def AreDispatchersSharable():
    return True

  def GetConnection(self, server, pool_name, health_cb, timeout):
    key = (server, pool_name)
    if key in _MUXERS:
      disp, cbs = _MUXERS[key]
    else:
      sock = THealthySocket(server.host, server.port, None, None, pool_name)
      disp = MuxMessageDispatcher(sock, timeout)
      cbs = set()
      _MUXERS[key] = (disp, cbs)

    if health_cb not in cbs:
      cbs.add(health_cb)
      disp.shutdown_result.rawlink(lambda ar: health_cb(server))

    return disp

  def IsConnectionFault(self, e):
    return isinstance(e,  TTransport.TTransportException)


class ThriftMux(object):
  @staticmethod
  def newService(Client, uri):
    """Create a new client for a ThriftMux service.

    Args:
      Client - The plain Thrift client (generated by the thrift compiler.)
      uri - The URI of the service.  Uri may be in the form of
            "tcp://host:port,host:port,...", or "zk://host:port/server/set/path".

    Returns:
      A proxy implementing all thrift methods of Client.
    """
    return Scales \
      .newBuilder(Client) \
      .setDispatcherFactory(MuxDispatcherProvider()) \
      .setUri(uri) \
      .build()
